// packages/bind-props-solid/src/index.tsx
import type { JSX } from 'solid-js';
import { createMemo } from 'solid-js';

export default function bindProps<
	Props extends {},
	BoundKeys extends keyof Props,
>(
	Component: (props: Props) => JSX.Element,
	boundProps: Pick<Props, BoundKeys>,
) {
	function ResultComponent(allProps: Omit<Props, BoundKeys>) {
		const merged = createMemo(
			() =>
				({
					...boundProps,
					...allProps,
				}) as Props,
		);

		return Component(merged());
	}

	return ResultComponent;
}

// packages/bind-props-react/src/index.tsx
import type { ReactElement } from 'react';
import React from 'react';

export default function bindProps<
	Props extends {},
	BoundKeys extends keyof Props,
>(
	Component: (props: Props) => ReactElement,
	boundProps: Pick<Props, BoundKeys>,
) {
	function ResultComponent(props: Omit<Props, BoundKeys>) {
		const mergedProps = { ...boundProps, ...props } as Props;
		return <Component {...mergedProps} />;
	}

	return ResultComponent;
}
